import type {AppSettings,PendingTask,TaskRecord} from "./model.js";import {DEFAULT_SETTINGS} from "./model.js";import {getPendingTasks,getSettings,getToken,savePendingTasks} from "./storage.js";import {addTask,getAttachment,getTasks} from "./repository.js";
let settings:AppSettings=DEFAULT_SETTINGS,records:TaskRecord[]=[],pending:PendingTask[]=[],adding=false;const retrying=new Set<number|string>();
const $=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;
function runtimeApi(){return (globalThis as any).browser?.runtime ?? (globalThis as any).chrome?.runtime;}
function openSettings(){runtimeApi()?.openOptionsPage?.();}
function bind(){$("connect").onclick=()=>openSettings();$("refresh").onclick=()=>void refresh();$("openSettings").onclick=()=>openSettings();$("add").onclick=()=>void addCurrentTask();$("attachment").addEventListener("change",()=>{$("attachmentName").textContent=(($("attachment") as HTMLInputElement).files?.[0]?.name??"");});for(let i=1;i<=5;i++)$<HTMLButtonElement>("difficulty-"+i).onclick=()=>setDifficulty(i);}
async function init(){try{settings=await getSettings();pending=await getPendingTasks();renderSettings();setDifficulty(0);await refresh();}catch(e){showError(e);}}
function setDifficulty(value:number){for(let i=1;i<=5;i++){const b=$<HTMLButtonElement>("difficulty-"+i);b.classList.toggle("selected",i<=value);b.setAttribute("aria-pressed",String(i<=value));}}
function selectedDifficulty(){for(let i=5;i>=1;i--)if($<HTMLButtonElement>("difficulty-"+i).classList.contains("selected"))return i;return 0;}
async function refresh(){clearError();$("refresh").setAttribute("disabled","");try{if(!(await getToken())){$("connection").textContent="Яндекс Диск не подключён";renderRecords();return;}$("connection").textContent="Яндекс Диск подключён";records=filter(await getTasks(settings));pending=await getPendingTasks();renderRecords();}catch(e){showError(e);}finally{$("refresh").removeAttribute("disabled");}}
function filter(all:TaskRecord[]){const s=[...all].sort((a,b)=>((a.date??"")+" "+(a.time??"")).localeCompare((b.date??"")+" "+(b.time??"")));if(settings.displayMode==="tasks")return s.slice(-settings.tasksToShow);const from=new Date();from.setHours(0,0,0,0);from.setDate(from.getDate()-settings.daysToShow+1);return s.filter(x=>x.date&&localDateObject(x.date)>=from);}
async function addCurrentTask(){const text=($("task") as HTMLTextAreaElement).value.trim();if(!text||adding)return;adding=true;($("add") as HTMLButtonElement).disabled=true;try{const now=new Date(),date=localDate(now),file=(($("attachment") as HTMLInputElement).files?.[0]);const suffix=file?"_"+crypto.randomUUID().replace(/-/g,"").slice(0,5):"";const target=file?file.name.replace(/(\.[^.]+)?$/,suffix+"$1"):undefined;const task:TaskRecord={id:crypto.randomUUID(),date,time:now.toTimeString().slice(0,8),weekday:["Пн","Вт","Ср","Чт","Пт","Сб","Вс"][now.getDay()===0?6:now.getDay()-1],partOfDay:partOfDay(now),taskType:($("type") as HTMLSelectElement).value,task:text,difficulty:selectedDifficulty(),attachmentFolder:file?((await import("./yandex.js")).attachmentFolder(settings,date)):undefined,attachmentName:target};const item:PendingTask={task,attachment:file?{name:file.name,type:file.type,data:await file.arrayBuffer()}:undefined,createdAt:`${Date.now()}-${crypto.randomUUID()}`};pending.push(item);try{await savePendingTasks(pending);}catch(e){pending=pending.filter(x=>x.createdAt!==item.createdAt);showError(new Error("Не удалось сохранить задачу в очередь: "+(e instanceof Error?e.message:String(e))));renderPending();return;}clearForm();renderRecords();await retry(item);}finally{adding=false;($("add") as HTMLButtonElement).disabled=false;}}
async function retry(item:PendingTask){if(retrying.has(item.createdAt))return;retrying.add(item.createdAt);try{if(item.attachment&&!item.attachment.data)throw new Error("Вложение в очереди отсутствует. Добавьте задачу заново.");await addTask(settings,item.task,item.attachment);pending=pending.filter(x=>x.createdAt!==item.createdAt);await savePendingTasks(pending);await refresh();}catch(e){showError(e);renderPending();}finally{retrying.delete(item.createdAt);}}
async function cancel(at:number|string){pending=pending.filter(x=>x.createdAt!==at);await savePendingTasks(pending);renderPending();}
function clearForm(){($("task") as HTMLTextAreaElement).value="";setDifficulty(0);($("attachment") as HTMLInputElement).value="";$("attachmentName").textContent="";}
function renderSettings(){$("period").textContent=settings.displayMode==="tasks"?"Последние "+settings.tasksToShow+" задач":"Последние "+settings.daysToShow+" дн.";const s=$("type") as HTMLSelectElement;s.innerHTML="";settings.taskTypes.forEach(t=>{const o=document.createElement("option");o.value=t.code;o.textContent=t.code;s.append(o);});}
function renderRecords(){const root=$("records");root.innerHTML="";records.forEach(r=>{const card=document.createElement("div");card.className="task-card";const meta=document.createElement("div");meta.className="task-meta";meta.textContent=(r.date??"")+" • "+r.taskType+" • "+("★".repeat(r.difficulty??0)||"0");const text=document.createElement("div");text.className="task-text";text.textContent=r.task;card.append(meta,text);if(r.attachmentName){const b=document.createElement("button");b.className="link-button";b.textContent="📎 "+r.attachmentName;b.onclick=()=>void openAttachment(r);card.append(b);}root.append(card);});renderPending();}
function renderPending(){const root=$("pending");root.innerHTML="";pending.forEach(p=>{const card=document.createElement("div");card.className="pending-card";const title=document.createElement("strong");title.textContent="Не отправлена в таблицу";const text=document.createElement("div");text.textContent=(p.task.date??"")+" • "+p.task.taskType+" • "+p.task.task;const actions=document.createElement("div");actions.className="actions";const c=document.createElement("button");c.textContent="Отменить";c.onclick=()=>void cancel(p.createdAt);const retryButton=document.createElement("button");retryButton.textContent=retrying.has(p.createdAt)?"Отправка...":"Повторить отправку";retryButton.disabled=retrying.has(p.createdAt);retryButton.onclick=()=>void retry(p);actions.append(c,retryButton);card.append(title,text,actions);root.append(card);});}
async function openAttachment(t:TaskRecord){const url="viewer.html?folder="+encodeURIComponent(t.attachmentFolder??"")+"&name="+encodeURIComponent(t.attachmentName??"");window.open(url,"_blank");}
function showError(e:unknown){$("error").textContent=e instanceof Error?e.message:String(e);$("error").hidden=false;}function clearError(){$("error").hidden=true;}
function localDate(d:Date){return [d.getFullYear(),String(d.getMonth()+1).padStart(2,"0"),String(d.getDate()).padStart(2,"0")].join("-");}
function localDateObject(s:string){const m=s.match(/^(\d{4})-(\d{2})-(\d{2})$/);return m?new Date(Number(m[1]),Number(m[2])-1,Number(m[3])):new Date(s);}
function partOfDay(d:Date){if(d.getHours()<8)return"До начала рабочего дня";if(d.getHours()<12)return"Утро";if(d.getHours()<15)return"Обед";if(d.getHours()<18)return"Вечер";return"После конца рабочего дня";}
bind();void init();