import type {AppSettings,TaskTypeDefinition} from "./model.js";import {clearLocalData,getSettings,saveSettings} from "./storage.js";import {connectToYandex,testConnection} from "./yandex.js";let settings:AppSettings;const $=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;
async function bindClick(id:string,handler:()=>void){const el=$(id);if(el)el.onclick=handler;}async function init(){try{settings=await getSettings();render();bindClick("save",()=>void save());bindClick("connect",()=>void connect());bindClick("testConnection",()=>void test());bindClick("clearCache",()=>void clearCache());bindClick("addType",()=>{syncTypesFromDom();settings.taskTypes.push({code:"Новый",description:""});render();};$("modeTasks").onchange=()=>{syncDisplayValue();syncTypesFromDom();settings.displayMode="tasks";render();};$("modeDays").onchange=()=>{syncDisplayValue();syncTypesFromDom();settings.displayMode="days";render();};}catch(e){const status=$("status");if(status)status.textContent="Ошибка загрузки настроек: "+(e instanceof Error?e.message:String(e));}}
function syncDisplayValue(){const n=Math.max(1,Number(($("tasks") as HTMLInputElement).value)||1);if(settings.displayMode==="tasks")settings.tasksToShow=n;else settings.daysToShow=n;}function syncTypesFromDom(){if(!settings)return;settings.taskTypes=Array.from(document.querySelectorAll(".type-row")).map(r=>({code:(r.querySelector('[data-role="code"]') as HTMLInputElement).value.trim(),description:(r.querySelector('[data-role="description"]') as HTMLInputElement).value.trim()}));}
function render(){$("diskPath").setAttribute("value",settings.diskPath);($("diskPath") as HTMLInputElement).value=settings.diskPath;const n=settings.displayMode==="tasks"?settings.tasksToShow:settings.daysToShow;($("tasks") as HTMLInputElement).value=String(n);($("modeTasks") as HTMLInputElement).checked=settings.displayMode==="tasks";($("modeDays") as HTMLInputElement).checked=settings.displayMode==="days";$("displayNumberLabel").textContent=settings.displayMode==="tasks"?"Количество задач":"Количество дней";const root=$("types");root.innerHTML="";settings.taskTypes.forEach((t,i)=>{const row=document.createElement("div");row.className="type-row";const code=document.createElement("input");code.value=t.code;code.dataset.role="code";const desc=document.createElement("input");desc.value=t.description;desc.dataset.role="description";const del=document.createElement("button");del.type="button";del.textContent="Удалить";del.onclick=()=>{syncTypesFromDom();settings.taskTypes.splice(i,1);render();};row.append(code,desc,del);root.append(row);});}
function collectSettings():AppSettings{syncDisplayValue();syncTypesFromDom();const diskPath=($("diskPath") as HTMLInputElement).value.trim();const tasksToShow=Math.max(1,Number(($("tasks") as HTMLInputElement).value)||10);const daysToShow=Math.max(1,settings.daysToShow||2);const displayMode=($("modeDays") as HTMLInputElement).checked?"days":"tasks";const taskTypes=settings.taskTypes.map(t=>({code:t.code.trim(),description:t.description.trim()}));if(!diskPath)throw new Error("Укажите полный путь к XLSX.");if(!taskTypes.length)throw new Error("Добавьте хотя бы один тип задачи.");if(taskTypes.some(t=>!t.code))throw new Error("У каждого типа задачи должен быть указан код.");const codes=taskTypes.map(t=>t.code.toLocaleLowerCase());if(new Set(codes).size!==codes.length)throw new Error("Коды типов задач не должны повторяться.");return {displayMode,tasksToShow:displayMode==="tasks"?tasksToShow:settings.tasksToShow,daysToShow:displayMode==="days"?tasksToShow:daysToShow,diskPath,taskTypes};}
async function clearCache(){if(!confirm("Сбросить локальные данные расширения? Будут удалены сохранённые настройки, токен Яндекс Диска и очередь незагруженных задач. Данные в XLSX на Яндекс Диске не удаляются."))return;try{await clearLocalData();settings=await getSettings();render();$("connectionStatus").textContent="Локальные данные сброшены. Подключите Яндекс Диск заново и сохраните настройки.";$("testResult").textContent="";$("status").textContent="Кэш и локальные данные сброшены.";}catch(e){$("status").textContent="Не удалось сбросить локальные данные: "+(e instanceof Error?e.message:String(e));}}
async function save(){try{settings=collectSettings();await saveSettings(settings);$("status").textContent="Настройки сохранены.";}catch(e){$("status").textContent="Не удалось сохранить настройки: "+(e instanceof Error?e.message:String(e));}}
async function connect(){($("connect") as HTMLButtonElement).disabled=true;try{await connectToYandex();$("connectionStatus").textContent="Яндекс Диск подключён. Теперь можно выполнить проверку подключения.";}catch(e){$("connectionStatus").textContent="Не удалось подключиться: "+(e instanceof Error?e.message:String(e));}finally{($("connect") as HTMLButtonElement).disabled=false;}}
async function test(){($("testConnection") as HTMLButtonElement).disabled=true;$("testResult").textContent="Проверка...";try{const current=collectSettings();const r=await testConnection(current);$("testResult").textContent=r.attachmentFolderExists?"Подключение работает. Основной файл доступен. Папка вложений найдена.":"Подключение работает. Основной файл доступен. Папка вложений пока не создана.";}catch(e){$("testResult").textContent="Проверка не пройдена: "+(e instanceof Error?e.message:String(e));}finally{($("testConnection") as HTMLButtonElement).disabled=false;}}
void init();
