import * as XLSX from "xlsx-republish"; import type {TaskRecord} from "./model.js";
const headers=["ID","Дата","Время","День недели","Часть дня","Вид задачи","Задача","Сложность","Папка вложения","Файл вложения"];
function excelSerialToParts(v:number){const whole=Math.floor(v);const fraction=Math.max(0,Math.min(0.999999999,v-whole));const base=new Date(Date.UTC(1899,11,30)+whole*86400000);const total=Math.round(fraction*86400);return {year:base.getUTCFullYear(),month:base.getUTCMonth()+1,day:base.getUTCDate(),hour:Math.floor(total/3600)%24,minute:Math.floor(total/60)%60,second:total%60};}
const date=(v:any)=>{if(typeof v==="number"&&Number.isFinite(v)){const p=excelSerialToParts(v);return [p.year,String(p.month).padStart(2,"0"),String(p.day).padStart(2,"0")].join("-");}if(v instanceof Date&&!isNaN(v.getTime()))return [v.getUTCFullYear(),String(v.getUTCMonth()+1).padStart(2,"0"),String(v.getUTCDate()).padStart(2,"0")].join("-");const s=String(v??"").trim();const m=s.match(/^(\d{2})\.(\d{2})\.(\d{4})$/);if(m)return m[3]+"-"+m[2]+"-"+m[1];return s.match(/^\d{4}-\d{2}-\d{2}/)?.[0];};
const time=(v:any)=>{if(typeof v==="number"&&Number.isFinite(v)){const p=excelSerialToParts(v);return [p.hour,p.minute,p.second].map(x=>String(x).padStart(2,"0")).join(":");}if(v instanceof Date&&!isNaN(v.getTime()))return [v.getUTCHours(),v.getUTCMinutes(),v.getUTCSeconds()].map(x=>String(x).padStart(2,"0")).join(":");const s=String(v??"").trim();if(/^\d{1,2}:\d{2}$/.test(s))return s+":00";if(/^\d{1,2}:\d{2}:\d{2}$/.test(s))return s;return s||undefined;};
function rows(data:ArrayBuffer){const wb=XLSX.read(data,{type:"array",cellDates:false,raw:true});const ws=wb.Sheets[wb.SheetNames[0]];if(!ws)throw new Error("В XLSX отсутствует первый лист.");return {wb,ws,rows:XLSX.utils.sheet_to_json<any[]>(ws,{header:1,defval:"",raw:true,blankrows:true})};}
function hasValue(v:any){return v!==undefined&&v!==null&&String(v).trim()!=="";}
function lastDataRow(rows:any[][]){for(let i=rows.length-1;i>=1;i--)if((rows[i]??[]).some(hasValue))return i;return 0;}
export function readTasks(data:ArrayBuffer):TaskRecord[]{const {rows:r}=rows(data),h=(r[0]??[]).map(x=>String(x).trim()),ix=(n:string,f:number)=>h.indexOf(n)>=0?h.indexOf(n):f;const i={id:ix("ID",0),date:ix("Дата",1),time:ix("Время",2),weekday:ix("День недели",3),part:ix("Часть дня",4),type:ix("Вид задачи",5),task:ix("Задача",6),difficulty:ix("Сложность",7),folder:ix("Папка вложения",8),file:ix("Файл вложения",9)};return r.slice(1).map(x=>({id:String(x[i.id]??"").trim()||undefined,date:date(x[i.date]),time:time(x[i.time]),weekday:String(x[i.weekday]??""),partOfDay:String(x[i.part]??""),taskType:String(x[i.type]??""),task:String(x[i.task]??""),difficulty:Number.parseInt(String(x[i.difficulty]??""),10)||0,attachmentFolder:String(x[i.folder]??"").trim()||undefined,attachmentName:String(x[i.file]??"").trim()||undefined})).filter(x=>x.task.trim());}
export function appendTask(data:ArrayBuffer,t:TaskRecord):ArrayBuffer{const {wb,ws,rows:r}=rows(data);const h=(r[0]??[]).map(x=>String(x).trim());if(h[0]!=="ID")throw new Error("В XLSX отсутствует первая колонка ID. Добавьте колонку «ID» перед колонкой «Дата».");while(h.length<10)h.push(headers[h.length]);XLSX.utils.sheet_add_aoa(ws,[h],{origin:{r:0,c:0}});const lastRow=lastDataRow(r);const last=r[lastRow]??[];const id=(Number.parseInt(String(last[0]??""),10)||0)+1;const d=t.date??new Date().toISOString().slice(0,10),p=d.split("-");const row=[id,p[2]+"."+p[1]+"."+p[0],(t.time??"00:00:00").length===5?(t.time??"00:00")+":00":t.time,t.weekday,t.partOfDay,t.taskType,t.task,t.difficulty??0,t.attachmentFolder??"",t.attachmentName??""];XLSX.utils.sheet_add_aoa(ws,[row],{origin:{r:lastRow+1,c:0}});return XLSX.write(wb,{type:"array",bookType:"xlsx"}) as ArrayBuffer;}
