import type {AppSettings} from "./model.js"; import {getToken,saveToken} from "./storage.js";
const CLIENT_ID="f4ce4570ab454ee38f6792c37e61811d"; const REDIRECT="https://oauth.yandex.ru/verification_code"; const SCOPE="cloud_api:disk.read cloud_api:disk.write";
function random(n=48){return [...crypto.getRandomValues(new Uint8Array(n))].map(x=>(x%36).toString(36)).join("");}
async function challenge(v:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return btoa(String.fromCharCode(...new Uint8Array(d))).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"");}
export async function connectToYandex(){const verifier=random(),state=random(32),url=new URL("https://oauth.yandex.ru/authorize");url.searchParams.set("response_type","code");url.searchParams.set("client_id",CLIENT_ID);url.searchParams.set("redirect_uri",REDIRECT);url.searchParams.set("scope",SCOPE);url.searchParams.set("code_challenge",await challenge(verifier));url.searchParams.set("code_challenge_method","S256");url.searchParams.set("state",state);url.searchParams.set("force_confirm","yes");window.open(url.toString(),"_blank");const code=window.prompt("После авторизации вставьте сюда код подтверждения Яндекс OAuth:");if(!code?.trim())throw new Error("Авторизация отменена.");const body=new URLSearchParams({grant_type:"authorization_code",code:code.trim(),client_id:CLIENT_ID,redirect_uri:REDIRECT,code_verifier:verifier});const r=await fetch("https://oauth.yandex.ru/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body});if(!r.ok)throw new Error("Яндекс OAuth: HTTP "+r.status+" "+await r.text());const j=await r.json() as {access_token?:string};if(!j.access_token)throw new Error("Яндекс OAuth не вернул access_token.");await saveToken(j.access_token);}
async function api(url:string,init:RequestInit={}):Promise<Response>{const token=await getToken();if(!token)throw new Error("Яндекс Диск не подключён.");const h=new Headers(init.headers);h.set("Authorization","OAuth "+token);const r=await fetch(url,{...init,headers:h});if(r.status===401)throw new Error("Токен Яндекс Диска недействителен. Подключите аккаунт заново.");return r;}
async function href(op:string,path:string,extra=""){const r=await api("https://cloud-api.yandex.net/v1/disk/"+op+"?path="+encodeURIComponent(path)+extra);if(!r.ok)throw new Error("Яндекс Диск: HTTP "+r.status+" "+await r.text());const j=await r.json() as {href?:string};if(!j.href)throw new Error("Яндекс Диск не вернул ссылку операции.");return j.href;}
export async function downloadWorkbook(s:AppSettings){const r=await api(await href("resources/download",s.diskPath));if(!r.ok)throw new Error("Не удалось скачать XLSX: HTTP "+r.status);return r.arrayBuffer();}
export async function uploadWorkbook(s:AppSettings,data:ArrayBuffer){const r=await api(await href("resources/upload",s.diskPath,"&overwrite=true"),{method:"PUT",headers:{"Content-Type":"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"},body:data});if(!r.ok)throw new Error("Не удалось загрузить XLSX: HTTP "+r.status+" "+await r.text());}
export async function folderExists(path:string){const r=await api("https://cloud-api.yandex.net/v1/disk/resources?path="+encodeURIComponent(path));if(r.status===404)return false;if(!r.ok)throw new Error("Яндекс Диск: HTTP "+r.status+" "+await r.text());return ((await r.json()) as {type?:string}).type==="dir";}
export async function ensureFolder(path:string){const r=await api("https://cloud-api.yandex.net/v1/disk/resources?path="+encodeURIComponent(path),{method:"PUT"});if(r.ok)return;if(r.status===409&&await folderExists(path))return;throw new Error("Не удалось создать папку "+path+": HTTP "+r.status+" "+await r.text());}
export function attachmentFolder(s:AppSettings,date:string){const p=s.diskPath.substring(0,s.diskPath.lastIndexOf("/"));const [y,m]=date.split("-");return p+"/attached/"+y+"/"+m;}
export async function createAttachmentFolders(folder:string){const y=folder.substring(0,folder.lastIndexOf("/"));const a=y.substring(0,y.lastIndexOf("/"));await ensureFolder(a);await ensureFolder(y);await ensureFolder(folder);}
export async function uploadAttachment(path:string,data:ArrayBuffer,type:string){const r=await api(await href("resources/upload",path,"&overwrite=true"),{method:"PUT",headers:{"Content-Type":type||"application/octet-stream"},body:data});if(!r.ok)throw new Error("Не удалось загрузить вложение: HTTP "+r.status);}
export async function downloadFile(path:string){const r=await api(await href("resources/download",path));if(!r.ok)throw new Error("Не удалось скачать файл: HTTP "+r.status);return r.arrayBuffer();}
export async function testConnection(s:AppSettings){const b=await downloadWorkbook(s);if(!b.byteLength)throw new Error("Основной XLSX-файл пустой.");const f=s.diskPath.substring(0,s.diskPath.lastIndexOf("/"))+"/attached";return {filePath:s.diskPath,attachmentFolder:f,attachmentFolderExists:await folderExists(f)};}
/** Загружает JSON в указанный путь на Яндекс Диске, создавая ссылку на загрузку через API. */
export async function uploadAutotrackJson(path:string,content:string){
 const r=await api(await href("resources/upload",path,"&overwrite=true"),{method:"PUT",headers:{"Content-Type":"application/json; charset=utf-8"},body:content});
 if(!r.ok)throw new Error("Не удалось загрузить автотрекинг в "+path+": HTTP "+r.status+" "+await r.text());
}
